package com.zto.testcase.mapper.testcase;

import com.zto.testcase.model.UserRoleRelation;
import com.zto.testcase.model.UserRoleRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

public interface UserRoleRelationMapper {

    long countByExample(UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrolesrelation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrolesrelation
     *
     * @mbg.generated
     */
    int insert(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrolesrelation
     *
     * @mbg.generated
     */
    int insertSelective(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrolesrelation
     *
     * @mbg.generated
     */
    List<UserRoleRelation> selectByExample(UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrolesrelation
     *
     * @mbg.generated
     */
    UserRoleRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrolesrelation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrolesrelation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRoleRelation record);

    int deleteByUserId(String userId);

    int updateByUserId(@Param("userId") String userId, @Param("roleCode") String roleCode);
}